### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by mschauer** [mschauer/MitosisStochasticDiffEq.jl#10]
Now that the test show that this is all fine 🎉, some next steps

- [ ] Example: for example linear and non-linear continuous discrete smoother (van der Pol?)
- [ ] Consistency between argument names/order in Mitosis and MitosisStochasticDiffEq
- [ ] Merge `p` and `pest`?
- [ ] Use `WGaussian{(:μ, :Σ, :c)}` from Mitosis
- [ ] Ensemble version
- [ ] Doc-Strings

**Comment by frankschae** [comment]
> For non-centred reparametrizations we need to allow to give a fix Wiener process to the sampler.

This is just for the forward guiding, isn't it? Thus, by feeding a `NoiseProcess` from the `DiffEqNoiseProcess` package to `forwardguiding`, this is now implemented, too. For example, we can use a `NoiseGrid` in a MH sampler:
```julia
# random walk proposal for innovations
Zᵒ = ρ*Z + sqrt(1 - ρ^2)*randn(length(s))
Z1 = cumsum([0;sqrt(dt)*Zᵒ[1:end-1]])
NG = NoiseGrid(s,[[Z] for Z in Z1])

```
See:
https://github.com/mschauer/MitosisStochasticDiffEq.jl/blob/b66dcd6904d5726fe55b308595748dd653785895/src/guiding.jl#L112
and 
https://github.com/mschauer/MitosisStochasticDiffEq.jl/blob/main/test/guiding_test.jl#L319-L325
